[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'jeffreyiacono/vim-colors-wombat'
 
[[plugins]]
repo = 'Shougo/neocomplete.vim'
insert = 1

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 
  \   'colorscheme': 'wombat'
  \ }
'''
